# Generated by Django 4.2.15 on 2024-08-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='owner',
            new_name='user',
        ),
    ]
